spring:
  application:
    name: NotificationService

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: "0000"

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: notification-group

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

server:
  port: 8085