spring:
  application:
    name: PaymentService

  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: "0000"

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8085